language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
before_script: "pip install flake8"
script:
  - flake8 --max-line-length=120 src
  - cd src
  - python -m unittest discover
